/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FormRouteImport } from './routes/form'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoutingItemsRouteImport } from './routes/routing.items'
import { Route as RoutingItemsIndexRouteImport } from './routes/routing.items.index'
import { Route as RoutingItemsGamingRouteImport } from './routes/routing.items.gaming'
import { Route as RoutingItemsElectronicsRouteImport } from './routes/routing.items.electronics'
import { Route as RoutingItemsClothingRouteImport } from './routes/routing.items.clothing'
import { Route as RoutingItemsBooksRouteImport } from './routes/routing.items.books'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FormRoute = FormRouteImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutingItemsRoute = RoutingItemsRouteImport.update({
  id: '/routing/items',
  path: '/routing/items',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutingItemsIndexRoute = RoutingItemsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RoutingItemsRoute,
} as any)
const RoutingItemsGamingRoute = RoutingItemsGamingRouteImport.update({
  id: '/gaming',
  path: '/gaming',
  getParentRoute: () => RoutingItemsRoute,
} as any)
const RoutingItemsElectronicsRoute = RoutingItemsElectronicsRouteImport.update({
  id: '/electronics',
  path: '/electronics',
  getParentRoute: () => RoutingItemsRoute,
} as any)
const RoutingItemsClothingRoute = RoutingItemsClothingRouteImport.update({
  id: '/clothing',
  path: '/clothing',
  getParentRoute: () => RoutingItemsRoute,
} as any)
const RoutingItemsBooksRoute = RoutingItemsBooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => RoutingItemsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/form': typeof FormRoute
  '/login': typeof LoginRoute
  '/routing/items': typeof RoutingItemsRouteWithChildren
  '/routing/items/books': typeof RoutingItemsBooksRoute
  '/routing/items/clothing': typeof RoutingItemsClothingRoute
  '/routing/items/electronics': typeof RoutingItemsElectronicsRoute
  '/routing/items/gaming': typeof RoutingItemsGamingRoute
  '/routing/items/': typeof RoutingItemsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/form': typeof FormRoute
  '/login': typeof LoginRoute
  '/routing/items/books': typeof RoutingItemsBooksRoute
  '/routing/items/clothing': typeof RoutingItemsClothingRoute
  '/routing/items/electronics': typeof RoutingItemsElectronicsRoute
  '/routing/items/gaming': typeof RoutingItemsGamingRoute
  '/routing/items': typeof RoutingItemsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/form': typeof FormRoute
  '/login': typeof LoginRoute
  '/routing/items': typeof RoutingItemsRouteWithChildren
  '/routing/items/books': typeof RoutingItemsBooksRoute
  '/routing/items/clothing': typeof RoutingItemsClothingRoute
  '/routing/items/electronics': typeof RoutingItemsElectronicsRoute
  '/routing/items/gaming': typeof RoutingItemsGamingRoute
  '/routing/items/': typeof RoutingItemsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/form'
    | '/login'
    | '/routing/items'
    | '/routing/items/books'
    | '/routing/items/clothing'
    | '/routing/items/electronics'
    | '/routing/items/gaming'
    | '/routing/items/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/form'
    | '/login'
    | '/routing/items/books'
    | '/routing/items/clothing'
    | '/routing/items/electronics'
    | '/routing/items/gaming'
    | '/routing/items'
  id:
    | '__root__'
    | '/'
    | '/form'
    | '/login'
    | '/routing/items'
    | '/routing/items/books'
    | '/routing/items/clothing'
    | '/routing/items/electronics'
    | '/routing/items/gaming'
    | '/routing/items/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FormRoute: typeof FormRoute
  LoginRoute: typeof LoginRoute
  RoutingItemsRoute: typeof RoutingItemsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form': {
      id: '/form'
      path: '/form'
      fullPath: '/form'
      preLoaderRoute: typeof FormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routing/items': {
      id: '/routing/items'
      path: '/routing/items'
      fullPath: '/routing/items'
      preLoaderRoute: typeof RoutingItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routing/items/': {
      id: '/routing/items/'
      path: '/'
      fullPath: '/routing/items/'
      preLoaderRoute: typeof RoutingItemsIndexRouteImport
      parentRoute: typeof RoutingItemsRoute
    }
    '/routing/items/gaming': {
      id: '/routing/items/gaming'
      path: '/gaming'
      fullPath: '/routing/items/gaming'
      preLoaderRoute: typeof RoutingItemsGamingRouteImport
      parentRoute: typeof RoutingItemsRoute
    }
    '/routing/items/electronics': {
      id: '/routing/items/electronics'
      path: '/electronics'
      fullPath: '/routing/items/electronics'
      preLoaderRoute: typeof RoutingItemsElectronicsRouteImport
      parentRoute: typeof RoutingItemsRoute
    }
    '/routing/items/clothing': {
      id: '/routing/items/clothing'
      path: '/clothing'
      fullPath: '/routing/items/clothing'
      preLoaderRoute: typeof RoutingItemsClothingRouteImport
      parentRoute: typeof RoutingItemsRoute
    }
    '/routing/items/books': {
      id: '/routing/items/books'
      path: '/books'
      fullPath: '/routing/items/books'
      preLoaderRoute: typeof RoutingItemsBooksRouteImport
      parentRoute: typeof RoutingItemsRoute
    }
  }
}

interface RoutingItemsRouteChildren {
  RoutingItemsBooksRoute: typeof RoutingItemsBooksRoute
  RoutingItemsClothingRoute: typeof RoutingItemsClothingRoute
  RoutingItemsElectronicsRoute: typeof RoutingItemsElectronicsRoute
  RoutingItemsGamingRoute: typeof RoutingItemsGamingRoute
  RoutingItemsIndexRoute: typeof RoutingItemsIndexRoute
}

const RoutingItemsRouteChildren: RoutingItemsRouteChildren = {
  RoutingItemsBooksRoute: RoutingItemsBooksRoute,
  RoutingItemsClothingRoute: RoutingItemsClothingRoute,
  RoutingItemsElectronicsRoute: RoutingItemsElectronicsRoute,
  RoutingItemsGamingRoute: RoutingItemsGamingRoute,
  RoutingItemsIndexRoute: RoutingItemsIndexRoute,
}

const RoutingItemsRouteWithChildren = RoutingItemsRoute._addFileChildren(
  RoutingItemsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FormRoute: FormRoute,
  LoginRoute: LoginRoute,
  RoutingItemsRoute: RoutingItemsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
